"""Deterministic report renderer.

Converts ValidatedFindings into a structured Markdown security report.
No LLM involvement — every string in the report is derived mechanically
from the ValidatedFinding fields. The PoC curl command is built from the
evidence in the HarEntry, not generated by the model.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from bola_ai.agent.validator import ValidatedFinding
from bola_ai.rag.har_extractor import StructuredArtifact, HarEntry
from bola_ai.logging_config import get_logger

logger = get_logger("report_renderer")

_PATTERN_NAMES: dict[str, str] = {
    "1.1":  "ID in path without ownership check",
    "1.2":  "Related or linked resources",
    "1.3":  "Bulk or list endpoints",
    "1.4":  "Third-party or storage APIs",
    "1.5":  "Multi-tenant / cross-tenant access",
    "1.6":  "Write operations without ownership check",
    "1.7":  "Nested resources without parent authorization",
    "1.8":  "Predictable or sequential IDs",
    "1.9":  "Batch/bulk lookup endpoints",
    "1.10": "Cross-service identity propagation drift",
    "1.11": "Cache-key authorization mismatch",
    "1.12": "Mass assignment via object fields",
    "1.13": "IoT/SCADA node and device ID manipulation",
    "10.1": "ID swap in own request",
    "10.2": "Parameter escalation (own session scope extension)",
    "10.3": "Temporary-ID hijacking",
    "10.4": "Lifecycle state bypass",
    "10.5": "Draft / non-published resource access",
    "10.6": "Subscription / webhook hijacking",
}

_SEVERITY_MAP: dict[str, str] = {
    "high":   "🔴 HIGH",
    "medium": "🟡 MEDIUM",
    "low":    "🟢 LOW",
}


@dataclass
class RenderedReport:
    markdown: str
    finding_count: int
    high_count: int
    medium_count: int
    low_count: int
    rejected_count: int


class ReportRenderer:
    """Builds the final Markdown report from validated findings."""

    def render(
        self,
        accepted: list[ValidatedFinding],
        rejected: list[ValidatedFinding],
        artifact: StructuredArtifact,
    ) -> RenderedReport:
        entry_map: dict[int, HarEntry] = {e.id: e for e in artifact.entries}
        lines: list[str] = []

        high = [f for f in accepted if f.raw.confidence == "high"]
        medium = [f for f in accepted if f.raw.confidence == "medium"]
        low = [f for f in accepted if f.raw.confidence == "low"]

        lines.append("# BOLA Security Analysis Report")
        lines.append("")
        lines.append(f"**Artifact type:** HAR  "
                     f"**Entries analyzed:** {artifact.entry_count}  "
                     f"**Findings:** {len(accepted)}  "
                     f"**Rejected (unverified):** {len(rejected)}")
        lines.append("")

        if not accepted:
            lines.append("_No BOLA vulnerabilities detected._")
            if rejected:
                self._append_rejected_section(lines, rejected)
            return RenderedReport(
                markdown="\n".join(lines),
                finding_count=0,
                high_count=0, medium_count=0, low_count=0,
                rejected_count=len(rejected),
            )

        lines.append("## Summary")
        lines.append("")
        lines.append(f"| Severity | Count |")
        lines.append(f"|----------|-------|")
        lines.append(f"| 🔴 HIGH   | {len(high)} |")
        lines.append(f"| 🟡 MEDIUM | {len(medium)} |")
        lines.append(f"| 🟢 LOW    | {len(low)} |")
        lines.append("")

        for priority_group, label in [
            (high,   "High Severity"),
            (medium, "Medium Severity"),
            (low,    "Low Severity"),
        ]:
            if not priority_group:
                continue
            lines.append(f"## {label} Findings")
            lines.append("")
            for i, vf in enumerate(priority_group, start=1):
                self._append_finding(lines, vf, entry_map)

        if rejected:
            self._append_rejected_section(lines, rejected)

        return RenderedReport(
            markdown="\n".join(lines),
            finding_count=len(accepted),
            high_count=len(high),
            medium_count=len(medium),
            low_count=len(low),
            rejected_count=len(rejected),
        )

    def _append_finding(
        self,
        lines: list[str],
        vf: ValidatedFinding,
        entry_map: dict[int, HarEntry],
    ) -> None:
        raw = vf.raw
        pattern_name = _PATTERN_NAMES.get(raw.pattern_id, raw.pattern_name)
        severity = _SEVERITY_MAP.get(raw.confidence, raw.confidence.upper())
        entry = entry_map.get(raw.poc_entry_id) or entry_map.get(raw.entry_id)

        lines.append(f"### [{raw.pattern_id}] {pattern_name}")
        lines.append("")
        lines.append(f"**Severity:** {severity}")
        lines.append("")
        lines.append(f"**Evidence (entry [{raw.entry_id}]):**")
        lines.append(f"> `{raw.evidence_quote}`")
        lines.append("")
        lines.append(f"**Attack vector:**")
        lines.append(f"{raw.attack_delta}")
        lines.append("")
        if raw.note:
            lines.append(f"**Note:** {raw.note}")
            lines.append("")

        if entry:
            curl = self._build_curl(entry)
            if curl:
                lines.append(f"**PoC curl:**")
                lines.append(f"```bash")
                lines.append(curl)
                lines.append(f"```")
                lines.append("")

    def _append_rejected_section(
        self,
        lines: list[str],
        rejected: list[ValidatedFinding],
    ) -> None:
        lines.append("## Unverified Findings (Failed Validation)")
        lines.append("")
        lines.append("_These findings were produced by the model but could not be "
                     "mechanically verified against the HAR. Review manually._")
        lines.append("")
        for vf in rejected:
            lines.append(f"- Entry [{vf.raw.entry_id}] pattern `{vf.raw.pattern_id}`: "
                         f"{vf.failure_reason}")

    def _build_curl(self, entry: HarEntry) -> Optional[str]:
        """Build a deterministic curl command from the HarEntry."""
        if not entry or not entry.url:
            return None

        parts = ["curl -i"]
        if entry.method != "GET":
            parts.append(f"-X {entry.method}")

        auth_val = next(
            (v for k, v in entry.request_headers.items()
             if k.lower() == "authorization"),
            None,
        )
        if auth_val:
            parts.append(f"-H 'Authorization: {auth_val}'")

        for hname, hval in entry.request_headers.items():
            if hname.lower() in {"x-tenant-id", "x-org-id", "x-organization-id",
                                  "x-workspace-id", "x-client-id", "x-user-id"}:
                parts.append(f"-H '{hname}: {hval}'")

        if entry.body_json:
            import json as _json
            body_str = _json.dumps(entry.body_json)
            parts.append("-H 'Content-Type: application/json'")
            parts.append(f"-d '{body_str}'")
        elif entry.body_params:
            params = "&".join(f"{k}={v}" for k, v in entry.body_params.items())
            parts.append("-H 'Content-Type: application/x-www-form-urlencoded'")
            parts.append(f"-d '{params}'")

        parts.append(f"'{entry.url}'")
        return " \\\n  ".join(parts)
