#!/usr/bin/env python3
"""Run recurring small-model teaching cycles with quality gates.

This script orchestrates a "teacher -> reviewer -> gate" loop from task packs
generated by ``scripts/generate_ai_training_tasks.py``.

The implementation is intentionally model-agnostic:
- default mode validates existing task packs and enforces acceptance gates
- optional ``--with-llm`` mode runs local Ollama generation/review calls

Outputs:
- accepted examples jsonl
- rejected examples jsonl
- cycle summary json (with acceptance rate delta vs prior run)
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from bola_ai.agent.llm import chat


@dataclass
class CycleRecord:
    task_id: str
    passed: bool
    reasons: list[str]
    artifact: str
    expected_response: str
    review: str
    metadata: dict[str, Any]


def _now_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def _strict_section_check(text: str, required_sections: list[str]) -> list[str]:
    misses: list[str] = []
    low = text.lower()
    for section in required_sections:
        if section.lower() not in low:
            misses.append(f"missing section: {section}")
    return misses


def _extract_paths(text: str) -> set[str]:
    raw = re.findall(r"/[A-Za-z0-9._{}\\-]+(?:/[A-Za-z0-9._{}\\-]+)+", text)
    return {p.rstrip(".,;:") for p in raw}


def _gate_phase1(artifact: str, expected_response: str) -> list[str]:
    reasons: list[str] = []
    reasons.extend(
        _strict_section_check(
            expected_response,
            ["## Findings", "## Verification Runbook", "## Grounding Self-check", "## Uncertainty"],
        )
    )
    low = expected_response.lower()
    if "token a" not in low or "token b" not in low:
        reasons.append("missing two-token verification markers (Token A / Token B)")
    if "without a token" in low or "invalid token" in low:
        reasons.append("invalid verification logic (auth-only token checks)")

    artifact_paths = _extract_paths(artifact)
    if artifact_paths:
        used_paths = _extract_paths(expected_response)
        if not used_paths:
            reasons.append("no grounded endpoint/object paths in expected response")
        else:
            unknown = sorted(p for p in used_paths if p not in artifact_paths)
            if unknown:
                reasons.append(f"ungrounded paths referenced: {', '.join(unknown[:3])}")
    return reasons


def _call_llm(system_prompt: str, user_prompt: str, model: str, timeout: float) -> str:
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    return chat(messages, model=model, timeout=timeout)


def _run_task(
    task: dict[str, Any], *, with_llm: bool, model: str, timeout: float
) -> CycleRecord:
    task_id = str(task.get("task_id", "TASK-UNKNOWN"))
    system_prompt = str(task.get("system_prompt", ""))
    scenario_prompt = str(task.get("scenario_prompt", ""))
    expected_prompt = str(task.get("expected_response_prompt", ""))
    review_prompt = str(task.get("review_prompt", ""))
    phase_instructions = str(task.get("phase_instructions", ""))
    metadata = dict(task.get("metadata", {}))

    if with_llm:
        artifact = _call_llm(system_prompt, scenario_prompt, model=model, timeout=timeout).strip()
        expected_user_prompt = (
            f"{phase_instructions}\n\n{expected_prompt}\n\nArtifact:\n{artifact}"
            if phase_instructions
            else f"{expected_prompt}\n\nArtifact:\n{artifact}"
        )
        expected_response = _call_llm(system_prompt, expected_user_prompt, model=model, timeout=timeout).strip()
        review_user_prompt = (
            f"{review_prompt}\n\nArtifact:\n{artifact}\n\nExpected response:\n{expected_response}"
        )
        review = _call_llm(system_prompt, review_user_prompt, model=model, timeout=timeout).strip()
    else:
        # Deterministic offline mode: synthesize a minimal grounded artifact/response.
        artifact = (
            f"{scenario_prompt}\n\n"
            "Documented endpoints:\n"
            "- GET /api/v1/records/{recordId}\n"
            "- PATCH /api/v1/records/{recordId}\n"
        )
        expected_response = (
            "## Findings\n"
            "- GET /api/v1/records/{recordId}: ownership check may be missing; verify with Token A and Token B.\n"
            "- PATCH /api/v1/records/{recordId}: write authorization may be missing; verify with Token A and Token B.\n\n"
            "## Verification Runbook\n"
            "1. Call GET /api/v1/records/{recordId} with Token A.\n"
            "2. Call GET /api/v1/records/{recordId} with Token B.\n"
            "3. Repeat for PATCH /api/v1/records/{recordId}.\n\n"
            "## Grounding Self-check\n"
            "- /api/v1/records/{recordId}\n\n"
            "## Uncertainty\n"
            "- Ownership policy details are not fully documented."
        )
        review = "OFFLINE-GATE: reviewer call skipped; deterministic gates only."

    reasons = _gate_phase1(artifact=artifact, expected_response=expected_response)
    if with_llm and "pass" not in review.lower():
        reasons.append("reviewer did not mark PASS")

    return CycleRecord(
        task_id=task_id,
        passed=not reasons,
        reasons=reasons,
        artifact=artifact,
        expected_response=expected_response,
        review=review,
        metadata=metadata,
    )


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _latest_summary(summary_dir: Path) -> dict[str, Any] | None:
    files = sorted(summary_dir.glob("teaching_cycle_summary_*.json"))
    if not files:
        return None
    try:
        return json.loads(files[-1].read_text(encoding="utf-8"))
    except Exception:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Run small-model teaching cycle gates.")
    parser.add_argument(
        "--task-pack",
        required=True,
        help="Path to task pack JSONL from generate_ai_training_tasks.py",
    )
    parser.add_argument(
        "--output-dir",
        default="data/training/ai_cycles",
        help="Directory for accepted/rejected outputs and summary",
    )
    parser.add_argument(
        "--with-llm",
        action="store_true",
        help="Use local Ollama model for generation/review calls",
    )
    parser.add_argument("--model", default="bola-analyzer", help="Model name for --with-llm mode")
    parser.add_argument("--timeout", type=float, default=240.0, help="Per-call timeout for --with-llm mode")
    args = parser.parse_args()

    task_pack = Path(args.task_pack).resolve()
    out_dir = Path(args.output_dir).resolve()
    if not task_pack.is_file():
        raise FileNotFoundError(f"Task pack not found: {task_pack}")

    tasks = _load_jsonl(task_pack)
    ts = _now_ts()
    accepted: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []

    for task in tasks:
        rec = _run_task(task, with_llm=args.with_llm, model=args.model, timeout=args.timeout)
        row = {
            "task_id": rec.task_id,
            "reasons": rec.reasons,
            "artifact": rec.artifact,
            "expected_response": rec.expected_response,
            "review": rec.review,
            "metadata": rec.metadata,
        }
        if rec.passed:
            accepted.append(row)
        else:
            rejected.append(row)

    accepted_path = out_dir / f"accepted_{ts}.jsonl"
    rejected_path = out_dir / f"rejected_{ts}.jsonl"
    _write_jsonl(accepted_path, accepted)
    _write_jsonl(rejected_path, rejected)

    total = len(tasks)
    accepted_count = len(accepted)
    acceptance_rate = (accepted_count / total) if total else 0.0

    previous = _latest_summary(out_dir)
    prev_rate = float(previous.get("acceptance_rate", 0.0)) if previous else 0.0
    summary = {
        "task_pack": str(task_pack),
        "with_llm": args.with_llm,
        "model": args.model if args.with_llm else "offline-gates-only",
        "total_tasks": total,
        "accepted": accepted_count,
        "rejected": len(rejected),
        "acceptance_rate": round(acceptance_rate, 4),
        "acceptance_rate_delta_vs_previous": round(acceptance_rate - prev_rate, 4),
        "accepted_path": str(accepted_path),
        "rejected_path": str(rejected_path),
    }
    summary_path = out_dir / f"teaching_cycle_summary_{ts}.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
