#!/usr/bin/env python3
"""
Run each live E2E pytest node one-by-one; write docs/live_e2e_test_timings.md.

  PYTHONPATH=src python scripts/run_live_e2e_tests_one_by_one.py
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "live_e2e_test_timings.md"

# Order: fast health/UI first, then e2e_llm, then issues (each heavy analyze)
NODEIDS = [
    "tests/test_api_live.py::TestLiveAPI::test_live_health",
    "tests/test_api_live.py::TestLiveAPI::test_live_ui",
    "tests/test_api_live.py::TestLiveAPI::test_live_ingest_then_analyze",
    "tests/test_e2e_llm.py::TestE2ELLM::test_llm_report_references_ingested_documentation",
    "tests/test_e2e_llm.py::TestE2ELLM::test_llm_report_contains_verification_steps",
    "tests/test_e2e_llm.py::TestE2ELLM::test_llm_report_is_bola_focused",
    "tests/test_e2e_llm.py::TestE2ELLM::test_llm_report_is_not_error_or_generic",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_does_not_reference_unknown_endpoints",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_bola_findings_are_authorization_related",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_rationale_focuses_on_ownership_not_auth",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_has_consistent_finding_structure",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_verification_steps_mention_two_tokens_or_two_users",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_verification_not_without_token",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_no_bold_wrapped_headings",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_identifies_graphql_bola",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_graphql_verification_uses_two_tokens",
    "tests/test_issues_resolved.py::TestIssuesResolved::test_report_soql_identifies_record_level_bola",
]


def main() -> int:
    os.chdir(ROOT)
    env = {**os.environ, "PYTHONPATH": str(ROOT / "src")}
    if os.environ.get("BOLA_AI_SKIP_LIVE_E2E", "").lower() in ("1", "true", "yes"):
        print("BOLA_AI_SKIP_LIVE_E2E set — live tests skip; timings not useful.", file=sys.stderr)
    rows: list[tuple[str, float, str]] = []
    for node in NODEIDS:
        p = ROOT / node.split("::")[0]
        if not p.is_file():
            print(f"Skip missing: {node}", file=sys.stderr)
            continue
        t0 = time.perf_counter()
        r = subprocess.run(
            [sys.executable, "-m", "pytest", node, "-q", "--tb=no"],
            cwd=ROOT,
            env=env,
        )
        elapsed = time.perf_counter() - t0
        status = "PASS" if r.returncode == 0 else "FAIL"
        rows.append((node, elapsed, status))
        print(f"{elapsed:8.1f}s  {status}  {node}", flush=True)

    lines = [
        "# Live E2E test timings (one-by-one)",
        "",
        f"Generated by `scripts/run_live_e2e_tests_one_by_one.py`. **Total wall time:** {sum(x[1] for x in rows):.1f}s.",
        "",
        "| Test | Seconds | Result |",
        "|------|--------:|--------|",
    ]
    for node, sec, st in rows:
        lines.append(f"| `{node}` | {sec:.1f} | {st} |")
    lines.append("")
    lines.append("See [PERFORMANCE_TESTING.md](PERFORMANCE_TESTING.md). Add new rows to `NODEIDS` in the script when tests are added.")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT}")
    return 0 if rows and all(x[2] == "PASS" for x in rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
