#!/usr/bin/env python3
"""Run recurring small-model teaching cycles with quality gates.

This script orchestrates a "teacher -> reviewer -> gate" loop from task packs
generated by ``scripts/generate_ai_training_tasks.py``.

The implementation is intentionally model-agnostic:
- default mode validates existing task packs and enforces acceptance gates
- optional ``--with-llm`` mode runs local Ollama generation/review calls
- ``--from-reviewing`` mode discovers tasks directly from the hierarchical
  reviewing folder (no pre-generated task pack required)

Outputs:
- accepted examples jsonl
- rejected examples jsonl
- cycle summary json (with acceptance rate delta vs prior run)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import sqlparse
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from bola_ai.agent.llm import chat


@dataclass
class CycleRecord:
    task_id: str
    passed: bool
    reasons: list[str]
    artifact: str
    expected_response: str
    review: str
    metadata: dict[str, Any]


def _now_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield json.loads(line)


def _strict_section_check(text: str, required_sections: list[str]) -> list[str]:
    misses: list[str] = []
    low = text.lower()
    for section in required_sections:
        if section.lower() not in low:
            misses.append(f"missing section: {section}")
    return misses


def _section_group_check(text: str, required_any_groups: list[list[str]]) -> list[str]:
    """Require at least one marker from each semantic section group."""
    misses: list[str] = []
    low = (text or "").lower()
    for group in required_any_groups:
        if not any(marker.lower() in low for marker in group):
            misses.append(f"missing section group: {' | '.join(group)}")
    return misses


def _extract_paths(text: str) -> set[str]:
    # Extracts base paths (e.g., /api/v1/users) ignoring query params or payloads.
    # This enforces "Endpoint Strictness" while permitting "Payload Freedom".
    raw = re.findall(r"/[A-Za-z0-9._{}\\-]+(?:/[A-Za-z0-9._{}\\-]+)+", text)
    return {p.rstrip(".,;:") for p in raw}


def _has_comparative_verification_markers(text_lower: str) -> bool:
    markers = (
        "auth_token_1",
        "auth_token_2",
        "two principal",
        "principal 1",
        "principal 2",
        "two identity",
        "two identities",
        "two user",
        "different user",
        "different role",
        "session 1",
        "session 2",
        "compare results",
        "comparative",
    )
    return any(m in text_lower for m in markers)


def _gate_phase1(artifact: str, expected_response: str) -> list[str]:
    reasons: list[str] = []
    
    # 1. Section-quality gate (flexible across legacy and new formats).
    # Requires semantic coverage, not one rigid heading template.
    reasons.extend(
        _section_group_check(
            expected_response,
            [
                ["## findings", "## potential findings", "### discovery", "discovery:", "priority findings"],
                ["evidence", "observation", "evidence map", "rationale"],
                ["verification", "investigation steps", "proof of concept", "reproduction"],
                ["secure outcome", "vulnerable outcome", "remediation"],
            ],
        )
    )
    
    low = expected_response.lower()
    
    # 2. Targeted BOLA Guardrails (Removed broad bias)
    # Only enforce comparative checks IF the model explicitly claims an object-boundary flaw.
    is_bola_claim = any(kw in low for kw in ("bola", "object-level", "broken object", "idor"))
    
    if is_bola_claim:
        if not _has_comparative_verification_markers(low):
            reasons.append("BOLA claim missing mandatory comparative verification markers (two principals/sessions)")
        if "without a token" in low or "invalid token" in low:
            reasons.append("BOLA verification improperly relies on invalid/missing tokens instead of crossing identity boundaries")

    # 3. Grounding / Endpoint Strictness Gate
    artifact_paths = _extract_paths(artifact)
    if artifact_paths:
        used_paths = _extract_paths(expected_response)
        if not used_paths:
            reasons.append("no grounded endpoint/object paths utilized in expected response")
        else:
            # We check if the base paths used by the LLM exist in the artifact.
            # Synthesized payloads (like ?admin=true) are ignored by the regex, granting payload freedom.
            unknown = sorted(p for p in used_paths if p not in artifact_paths)
            if unknown:
                reasons.append(f"ungrounded endpoints hallucinated: {', '.join(unknown[:3])}")
                
    return reasons


def _validate_artifact_syntax(artifact: str, metadata: dict[str, Any]) -> list[str]:
    reasons: list[str] = []
    artifact_type = str(metadata.get("artifact_type", "")).strip().lower()
    text = artifact.strip()
    if not text:
        return ["artifact is empty"]

    try:
        if artifact_type == "network log":
            parsed = json.loads(text)
            entries = (((parsed or {}).get("log") or {}).get("entries")) if isinstance(parsed, dict) else None
            if not isinstance(entries, list) or not entries:
                reasons.append("network log syntax gate: missing log.entries[]")
            return reasons

        if artifact_type == "schema":
            statements = sqlparse.parse(text)
            if not statements:
                reasons.append("sql syntax gate: parser returned no statements")
            low = text.lower()
            if "create table" not in low:
                reasons.append("sql syntax gate: expected CREATE TABLE statement")
            return reasons

        if artifact_type == "api documentation":
            parsed: Any
            if text.startswith("{") or text.startswith("["):
                parsed = json.loads(text)
            else:
                parsed = yaml.safe_load(text)
            if not isinstance(parsed, dict):
                reasons.append("api syntax gate: expected mapping object")
                return reasons
            if "paths" not in parsed:
                reasons.append("api syntax gate: missing paths object")
            if not any(k in parsed for k in ("openapi", "swagger")):
                reasons.append("api syntax gate: missing openapi/swagger version marker")
            return reasons
            
    except json.JSONDecodeError as exc:
        reasons.append(f"json syntax gate failed: {exc.msg}")
    except yaml.YAMLError:
        reasons.append("yaml syntax gate failed")
    except Exception as exc:
        reasons.append(f"syntax gate error: {exc}")

    return reasons


def _call_llm(system_prompt: str, user_prompt: str, model: str, timeout: float) -> str:
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    return chat(messages, model=model, timeout=timeout)


def _run_task(
    task: dict[str, Any], *, with_llm: bool, model: str, timeout: float
) -> CycleRecord:
    task_id = str(task.get("task_id", "TASK-UNKNOWN"))
    system_prompt = str(task.get("system_prompt", ""))
    scenario_prompt = str(task.get("scenario_prompt", ""))
    expected_prompt = str(task.get("expected_response_prompt", ""))
    review_prompt = str(task.get("review_prompt", ""))
    phase_instructions = str(task.get("phase_instructions", ""))
    metadata = dict(task.get("metadata", {}))
    artifact_template = str(task.get("artifact_template", "")).strip()

    if with_llm:
        scenario_user_prompt = scenario_prompt
        if artifact_template:
            scenario_user_prompt += (
                "\n\nTemplate wrapper (preserve syntax; fill with scenario logic and noise):\n"
                f"{artifact_template}"
            )
        artifact = _call_llm(system_prompt, scenario_user_prompt, model=model, timeout=timeout).strip()
        expected_user_prompt = (
            f"{phase_instructions}\n\n{expected_prompt}\n\nArtifact:\n{artifact}"
            if phase_instructions
            else f"{expected_prompt}\n\nArtifact:\n{artifact}"
        )
        expected_response = _call_llm(system_prompt, expected_user_prompt, model=model, timeout=timeout).strip()
        review_user_prompt = (
            f"{review_prompt}\n\nArtifact:\n{artifact}\n\nExpected response:\n{expected_response}"
        )
        review = _call_llm(system_prompt, review_user_prompt, model=model, timeout=timeout).strip()
    else:
        # Deterministic offline mode: Aligned to the new Wide-Spectrum format to pass its own gates.
        artifact = artifact_template or (
            f"{scenario_prompt}\n\n"
            "Documented endpoints:\n"
            "- GET /api/v1/telemetry/nodes/{nodeId}\n"
            "- PATCH /api/v1/telemetry/nodes/{nodeId}\n"
        )
        artifact_paths = sorted(_extract_paths(artifact))
        primary_path = artifact_paths[0] if artifact_paths else "/api/v1/telemetry/nodes/{nodeId}"
        
        expected_response = (
            f"## 🔍 Discovery: Broken Object-Level Authorization (BOLA)\n"
            f"**Type:** Investigative Lead\n"
            f"**Target:** {primary_path}\n\n"
            f"### 1. Threat Hypothesis\n"
            f"The endpoint {primary_path} accepts a nodeId, but documentation lacks evidence of tenant-ownership constraints. An attacker may manipulate telemetry for hardware they do not own.\n\n"
            f"### 2. Analyst Investigation Steps\n"
            f"1. Authenticate as a low-privileged operator (AUTH_TOKEN_1).\n"
            f"2. Identify a nodeId belonging to a different facility (AUTH_TOKEN_2).\n"
            f"3. Issue a request targeting the victim's nodeId and compare the results.\n\n"
            f"### 3. Proof of Concept (PoC) / Testing Methodology\n"
            f"```bash\n"
            f"curl -X GET '[https://api.infrastructure.local](https://api.infrastructure.local){primary_path}' \\\n"
            f"  -H 'Authorization: Bearer AUTH_TOKEN_1'\n"
            f"curl -X GET '[https://api.infrastructure.local](https://api.infrastructure.local){primary_path}' \\\n"
            f"  -H 'Authorization: Bearer AUTH_TOKEN_2'\n"
            f"```\n\n"
            f"**Expected Secure Outcome:** 403 Forbidden\n"
            f"**Expected Vulnerable Outcome:** 200 OK and external telemetry returned."
        )
        review = "OFFLINE-GATE: reviewer call skipped; deterministic gates only."

    reasons = _validate_artifact_syntax(artifact=artifact, metadata=metadata)
    reasons.extend(_gate_phase1(artifact=artifact, expected_response=expected_response))
    
    if with_llm and "pass" not in review.lower():
        reasons.append("reviewer did not mark PASS")

    return CycleRecord(
        task_id=task_id,
        passed=not reasons,
        reasons=reasons,
        artifact=artifact,
        expected_response=expected_response,
        review=review,
        metadata=metadata,
    )


def _append_jsonl_row(file_obj, row: dict[str, Any]) -> None:
    file_obj.write(json.dumps(row, ensure_ascii=False) + "\n")


def _latest_summary(summary_dir: Path) -> dict[str, Any] | None:
    files = sorted(summary_dir.glob("teaching_cycle_summary_*.json"))
    if not files:
        return None
    try:
        return json.loads(files[-1].read_text(encoding="utf-8"))
    except Exception:
        return None


def _iter_reviewing_tasks(reviewing_root: Path):
    """Yield task dicts from the hierarchical reviewing folder structure."""
    from training.reviewing_iter import iter_leaf_folders
    from training.ai_teacher_prompts import TEACHER_SYSTEM_PROMPT, EXPECTED_RESPONSE_PROMPT, REVIEW_PROMPT
    for leaf in iter_leaf_folders(reviewing_root):
        ctx_file  = leaf / "context.txt"
        resp_file = leaf / "expected_response.md"
        if not ctx_file.exists() or not resp_file.exists():
            continue
        artifact = ctx_file.read_text(encoding="utf-8")
        expected = resp_file.read_text(encoding="utf-8")
        expl_file = leaf / "analysis_explanation.md"
        task = {
            "task_id": f"REVIEW-{leaf.name}",
            "system_prompt": TEACHER_SYSTEM_PROMPT,
            "scenario_prompt": artifact,
            "expected_response_prompt": EXPECTED_RESPONSE_PROMPT,
            "review_prompt": REVIEW_PROMPT,
            "artifact_template": artifact,
            "gold_expected_response": expected,
            "metadata": {
                "source_folder": str(leaf),
                "phase": "reviewing",
                "blueprint": "from-reviewing",
            },
        }
        if expl_file.exists():
            task["analysis_explanation"] = expl_file.read_text(encoding="utf-8")
        yield task


def main() -> int:
    parser = argparse.ArgumentParser(description="Run small-model teaching cycle gates.")
    parser.add_argument(
        "--task-pack",
        default=None,
        help="Path to task pack JSONL from generate_ai_training_tasks.py",
    )
    parser.add_argument(
        "--from-reviewing",
        action="store_true",
        help="Discover tasks directly from data/training/reviewing hierarchy (no task pack needed)",
    )
    parser.add_argument(
        "--reviewing-root",
        default=None,
        help="Path to reviewing root (default: <repo>/data/training/reviewing)",
    )
    parser.add_argument(
        "--output-dir",
        default="data/training/ai_cycles",
        help="Directory for accepted/rejected outputs and summary",
    )
    parser.add_argument(
        "--with-llm",
        action="store_true",
        help="Use local Ollama model for generation/review calls",
    )
    parser.add_argument("--model", default="bola-analyzer", help="Model name for --with-llm mode")
    parser.add_argument("--timeout", type=float, default=240.0, help="Per-call timeout for --with-llm mode")
    args = parser.parse_args()

    if not args.from_reviewing and not args.task_pack:
        parser.error("Either --task-pack or --from-reviewing is required")

    out_dir = Path(args.output_dir).resolve()

    if args.from_reviewing:
        repo_root = Path(__file__).resolve().parents[1]
        reviewing_root = Path(args.reviewing_root).resolve() if args.reviewing_root else repo_root / "data" / "training" / "reviewing"
        task_iter = _iter_reviewing_tasks(reviewing_root)
        source_label = str(reviewing_root)
    else:
        task_pack = Path(args.task_pack).resolve()
        if not task_pack.is_file():
            raise FileNotFoundError(f"Task pack not found: {task_pack}")
        task_iter = _iter_jsonl(task_pack)
        source_label = str(task_pack)

    ts = _now_ts()
    accepted_count = 0
    rejected_count = 0
    total = 0

    accepted_path = out_dir / f"accepted_{ts}.jsonl"
    rejected_path = out_dir / f"rejected_{ts}.jsonl"
    accepted_path.parent.mkdir(parents=True, exist_ok=True)
    rejected_path.parent.mkdir(parents=True, exist_ok=True)

    with accepted_path.open("w", encoding="utf-8") as accepted_f, rejected_path.open("w", encoding="utf-8") as rejected_f:
        for task in task_iter:
            total += 1
            rec = _run_task(task, with_llm=args.with_llm, model=args.model, timeout=args.timeout)
            row = {
                "task_id": rec.task_id,
                "reasons": rec.reasons,
                "artifact": rec.artifact,
                "expected_response": rec.expected_response,
                "review": rec.review,
                "metadata": rec.metadata,
            }
            if rec.passed:
                _append_jsonl_row(accepted_f, row)
                accepted_count += 1
            else:
                _append_jsonl_row(rejected_f, row)
                rejected_count += 1

    acceptance_rate = (accepted_count / total) if total else 0.0

    previous = _latest_summary(out_dir)
    prev_rate = float(previous.get("acceptance_rate", 0.0)) if previous else 0.0
    summary = {
        "source": source_label,
        "from_reviewing": args.from_reviewing,
        "with_llm": args.with_llm,
        "model": args.model if args.with_llm else "offline-gates-only",
        "total_tasks": total,
        "accepted": accepted_count,
        "rejected": rejected_count,
        "acceptance_rate": round(acceptance_rate, 4),
        "acceptance_rate_delta_vs_previous": round(acceptance_rate - prev_rate, 4),
        "accepted_path": str(accepted_path),
        "rejected_path": str(rejected_path),
    }
    summary_path = out_dir / f"teaching_cycle_summary_{ts}.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())